/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.thelastcitadel.pru;

public interface PRUConstants {
  public final static int NUM_PRU_HOSTIRQS = PRUJNI.NUM_PRU_HOSTIRQS_get();
  public final static int NUM_PRU_HOSTS = PRUJNI.NUM_PRU_HOSTS_get();
  public final static int NUM_PRU_CHANNELS = PRUJNI.NUM_PRU_CHANNELS_get();
  public final static int NUM_PRU_SYS_EVTS = PRUJNI.NUM_PRU_SYS_EVTS_get();
  public final static int PRUSS0_PRU0_DATARAM = PRUJNI.PRUSS0_PRU0_DATARAM_get();
  public final static int PRUSS0_PRU1_DATARAM = PRUJNI.PRUSS0_PRU1_DATARAM_get();
  public final static int PRUSS0_PRU0_IRAM = PRUJNI.PRUSS0_PRU0_IRAM_get();
  public final static int PRUSS0_PRU1_IRAM = PRUJNI.PRUSS0_PRU1_IRAM_get();
  public final static int PRUSS0_SHARED_DATARAM = PRUJNI.PRUSS0_SHARED_DATARAM_get();
  public final static int PRUSS0_CFG = PRUJNI.PRUSS0_CFG_get();
  public final static int PRUSS0_UART = PRUJNI.PRUSS0_UART_get();
  public final static int PRUSS0_IEP = PRUJNI.PRUSS0_IEP_get();
  public final static int PRUSS0_ECAP = PRUJNI.PRUSS0_ECAP_get();
  public final static int PRUSS0_MII_RT = PRUJNI.PRUSS0_MII_RT_get();
  public final static int PRUSS0_MDIO = PRUJNI.PRUSS0_MDIO_get();
  public final static int PRU_EVTOUT_0 = PRUJNI.PRU_EVTOUT_0_get();
  public final static int PRU_EVTOUT_1 = PRUJNI.PRU_EVTOUT_1_get();
  public final static int PRU_EVTOUT_2 = PRUJNI.PRU_EVTOUT_2_get();
  public final static int PRU_EVTOUT_3 = PRUJNI.PRU_EVTOUT_3_get();
  public final static int PRU_EVTOUT_4 = PRUJNI.PRU_EVTOUT_4_get();
  public final static int PRU_EVTOUT_5 = PRUJNI.PRU_EVTOUT_5_get();
  public final static int PRU_EVTOUT_6 = PRUJNI.PRU_EVTOUT_6_get();
  public final static int PRU_EVTOUT_7 = PRUJNI.PRU_EVTOUT_7_get();
  public final static int PRU0_PRU1_INTERRUPT = PRUJNI.PRU0_PRU1_INTERRUPT_get();
  public final static int PRU1_PRU0_INTERRUPT = PRUJNI.PRU1_PRU0_INTERRUPT_get();
  public final static int PRU0_ARM_INTERRUPT = PRUJNI.PRU0_ARM_INTERRUPT_get();
  public final static int PRU1_ARM_INTERRUPT = PRUJNI.PRU1_ARM_INTERRUPT_get();
  public final static int ARM_PRU0_INTERRUPT = PRUJNI.ARM_PRU0_INTERRUPT_get();
  public final static int ARM_PRU1_INTERRUPT = PRUJNI.ARM_PRU1_INTERRUPT_get();
  public final static int CHANNEL0 = PRUJNI.CHANNEL0_get();
  public final static int CHANNEL1 = PRUJNI.CHANNEL1_get();
  public final static int CHANNEL2 = PRUJNI.CHANNEL2_get();
  public final static int CHANNEL3 = PRUJNI.CHANNEL3_get();
  public final static int CHANNEL4 = PRUJNI.CHANNEL4_get();
  public final static int CHANNEL5 = PRUJNI.CHANNEL5_get();
  public final static int CHANNEL6 = PRUJNI.CHANNEL6_get();
  public final static int CHANNEL7 = PRUJNI.CHANNEL7_get();
  public final static int CHANNEL8 = PRUJNI.CHANNEL8_get();
  public final static int CHANNEL9 = PRUJNI.CHANNEL9_get();
  public final static int PRU0 = PRUJNI.PRU0_get();
  public final static int PRU1 = PRUJNI.PRU1_get();
  public final static int PRU_EVTOUT0 = PRUJNI.PRU_EVTOUT0_get();
  public final static int PRU_EVTOUT1 = PRUJNI.PRU_EVTOUT1_get();
  public final static int PRU_EVTOUT2 = PRUJNI.PRU_EVTOUT2_get();
  public final static int PRU_EVTOUT3 = PRUJNI.PRU_EVTOUT3_get();
  public final static int PRU_EVTOUT4 = PRUJNI.PRU_EVTOUT4_get();
  public final static int PRU_EVTOUT5 = PRUJNI.PRU_EVTOUT5_get();
  public final static int PRU_EVTOUT6 = PRUJNI.PRU_EVTOUT6_get();
  public final static int PRU_EVTOUT7 = PRUJNI.PRU_EVTOUT7_get();
  public final static int PRU0_HOSTEN_MASK = PRUJNI.PRU0_HOSTEN_MASK_get();
  public final static int PRU1_HOSTEN_MASK = PRUJNI.PRU1_HOSTEN_MASK_get();
  public final static int PRU_EVTOUT0_HOSTEN_MASK = PRUJNI.PRU_EVTOUT0_HOSTEN_MASK_get();
  public final static int PRU_EVTOUT1_HOSTEN_MASK = PRUJNI.PRU_EVTOUT1_HOSTEN_MASK_get();
  public final static int PRU_EVTOUT2_HOSTEN_MASK = PRUJNI.PRU_EVTOUT2_HOSTEN_MASK_get();
  public final static int PRU_EVTOUT3_HOSTEN_MASK = PRUJNI.PRU_EVTOUT3_HOSTEN_MASK_get();
  public final static int PRU_EVTOUT4_HOSTEN_MASK = PRUJNI.PRU_EVTOUT4_HOSTEN_MASK_get();
  public final static int PRU_EVTOUT5_HOSTEN_MASK = PRUJNI.PRU_EVTOUT5_HOSTEN_MASK_get();
  public final static int PRU_EVTOUT6_HOSTEN_MASK = PRUJNI.PRU_EVTOUT6_HOSTEN_MASK_get();
  public final static int PRU_EVTOUT7_HOSTEN_MASK = PRUJNI.PRU_EVTOUT7_HOSTEN_MASK_get();
}
